/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stocks/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StockerFeaturesStockRankingEndpointsRankStocksEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StockerFeaturesStockRankingModelsRankingResponse: {
            /** Format: int32 */
            totalRanked?: number;
            /** Format: int32 */
            totalMissingCap?: number;
            rankedStocks?: components["schemas"]["StockerFeaturesStockRankingModelsStockDto"][];
            missingCapStocks?: components["schemas"]["StockerFeaturesStockRankingModelsStockDto"][];
        };
        StockerFeaturesStockRankingModelsStockDto: {
            name?: string;
            /** Format: int32 */
            combinedRank?: number;
            /** Format: int32 */
            peRank?: number;
            /** Format: int32 */
            roaRank?: number;
            /** Format: decimal */
            marketCap?: number | null;
            /** Format: decimal */
            price?: number | null;
            /** Format: decimal */
            change?: number | null;
            /** Format: int64 */
            volume?: number | null;
            /** Format: decimal */
            peRatio?: number | null;
            /** Format: decimal */
            eps?: number | null;
            /** Format: decimal */
            roa?: number | null;
            /** Format: decimal */
            dividendsYield?: number | null;
            description?: string | null;
            sector?: string | null;
            market?: string | null;
            stockExchange?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StockerFeaturesStockRankingEndpointsRankStocksEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockerFeaturesStockRankingModelsRankingResponse"];
                };
            };
        };
    };
}
