/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StockerFeaturesUserProfileGetUserProfileGetUserProfile"];
        put?: never;
        post: operations["StockerFeaturesUserProfileUpsertUserProfileUpsertUserProfileEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/upload-avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StockerFeaturesUserProfileUploadAvatarUploadAvatarEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StockerFeaturesStockStockRankingRankStocksEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StockerFeaturesUserProfileUpsertUserProfileUpsertUserProfileRequest: {
            image?: string;
            nickname?: string;
            phone?: string;
            address?: string;
        };
        /** @description the dto used to send an error response to the client */
        FastEndpointsErrorResponse: {
            /**
             * Format: int32
             * @description the http status code sent to the client. default is 400.
             * @default 400
             */
            statusCode: number;
            /**
             * @description the message for the error response
             * @default One or more errors occurred!
             */
            message: string;
            /** @description the collection of errors for the current context */
            errors?: {
                [key: string]: string[];
            };
        };
        StockerFeaturesUserProfileUploadAvatarUploadAvatarResponse: {
            imageKey?: string;
        };
        StockerFeaturesUserProfileGetUserProfileUserProfileResponse: {
            image?: string;
            avatarUrl?: string | null;
            nickname?: string;
            phone?: string;
            address?: string;
        };
        StockerFeaturesStockStockRankingRankingResponse: {
            /** Format: int32 */
            totalRanked?: number;
            /** Format: int32 */
            totalMissingCap?: number;
            rankedStocks?: components["schemas"]["StockerFeaturesStockStockRankingStock"][];
            missingCapStocks?: components["schemas"]["StockerFeaturesStockStockRankingStock"][];
        };
        StockerFeaturesStockStockRankingStock: {
            name?: string;
            /** Format: int32 */
            combinedRank?: number;
            /** Format: int32 */
            peRank?: number;
            /** Format: int32 */
            roicRank?: number;
            /** Format: decimal */
            marketCap?: number | null;
            /** Format: decimal */
            price?: number | null;
            /** Format: decimal */
            change?: number | null;
            /** Format: int64 */
            volume?: number | null;
            /** Format: decimal */
            peRatio?: number | null;
            /** Format: decimal */
            eps?: number | null;
            /** Format: decimal */
            roic?: number | null;
            /** Format: decimal */
            dividendsYield?: number | null;
            description?: string | null;
            sector?: string | null;
            market?: string | null;
            stockExchange?: string | null;
        };
        StockerFeaturesStockStockRankingRankingRequest: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StockerFeaturesUserProfileGetUserProfileGetUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockerFeaturesUserProfileGetUserProfileUserProfileResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockerFeaturesUserProfileUpsertUserProfileUpsertUserProfileEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockerFeaturesUserProfileUpsertUserProfileUpsertUserProfileRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["FastEndpointsErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockerFeaturesUserProfileUploadAvatarUploadAvatarEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockerFeaturesUserProfileUploadAvatarUploadAvatarResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StockerFeaturesStockStockRankingRankStocksEndpoint: {
        parameters: {
            query: {
                numberOfStocks: number;
                minimumMarketCap?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockerFeaturesStockStockRankingRankingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["FastEndpointsErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
