apiVersion: 1

datasources:
  # 1. Prometheus (Metrics)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST

  # 2. Loki (Logs)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      # This block tells Grafana how to find a TraceId inside your .NET logs
      # and turns it into a clickable shortcut straight into Tempo!
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # 3. Tempo (Traces)
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
